spring.application.name=SpringSecurity
spring.security.user.name=pokemon
spring.security.user.password=1234


spring.datasource.url=jdbc:postgresql://localhost:5432/StudentsInfo
spring.datasource.username=postgres
spring.datasource.password=Evans#123

